### ISSUE TITLE
UI error

### ISSUE THREAD

**Issue by ttyhgo** [ReportSubmit/KMUScoreServer#18]
UI 너비에 따라 버튼이 사라졌다 나타남

**Comment by ReportSubmit** [comment]
이 에러는 css 안에 icon-bar class가 없어서 발생

![image](https://cloud.githubusercontent.com/assets/13326991/21483268/97115eb4-cbc2-11e6-8b61-255cefeb3c46.png)

![image](https://cloud.githubusercontent.com/assets/13326991/21483219/02565040-cbc2-11e6-9d60-bc3225e3068e.png)
